### ISSUE TITLE
Bug: if you will have more than one key-value pair in dictionary you will execute next delegate multiple times

### ISSUE THREAD

**Issue by vvvictor07** [TourmalineCore/TourmalineCore.Serilog.AspNetCore.Middlewares#1]
In [LoggingMiddleware.cs](https://github.com/TourmalineCore/TourmalineCore.Serilog.AspNetCore.Middlewares/blob/develop/TourmalineCore.Serilog.AspNetCore.Middlewares/Middlewares/LoggingMiddleware.cs) you should push all values to the `_diagnosticContext` and `LogContext` before executing `await _next(httpContext)`
```c#
                foreach (var (key, value) in loggingValues)
                {
                    _diagnosticContext.Set(key, value);

                    using (LogContext.PushProperty(key, value))
                    {
                        await _next(httpContext);
                    }
                }
```

**Comment by iamvladislove** [comment]
Fixed this issue in v1.0.0-alpha.3.
Release link - https://github.com/TourmalineCore/TourmalineCore.Serilog.AspNetCore.Middlewares/releases/tag/v1.0.0-alpha.3
